name: my_dir

# current directory that SSL_VIDEO is located
current: /home/as89480@ens.ad.etsmtl.ca/projects/SSL_video

model_path: /home/as89480@ens.ad.etsmtl.ca/projects/SSL_video/models

# Dataset directory
PATH_PREFIX: /home/as89480@ens.ad.etsmtl.ca/projects/SSL_video/dataset/k400