name: my_dir

# current directory that SSL_VIDEO is located
current: /home/sdastani/projects/rrg-ebrahimi/sdastani/SSL_video

model_path: /home/sdastani/projects/rrg-ebrahimi/sdastani/SSL_video/models

# Dataset directory
PATH_PREFIX: /home/sdastani/projects/rrg-ebrahimi/sdastani/SSL_video/k400

