defaults:
  - _self_
  - dataset: kinetics
  - feature_extractor: resnet2d1
  - model: vicregl

wandb:
  mode: offline
  project: video_ssl_project
  entity: null
  name: global_seed/test1
  group: null 
  tags: null 
  notes: null 

common:
  seed: 100

split: 'train'

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}