defaults:
  - _self_
  - dataset: kinetics
  - feature_extractor: resnet2d1
  - model: vicregl
  - dirs: my_dir

wandb:
  mode: offline
  project: video_ssl_project
  entity: null
  name: localtest1
  group: ResNet 
  tags: null 
  notes: null 

initialization:
  path_to_checkpoint: null 

common:
  device: "cuda"
  batch_size: 2
  epochs: 1
  seed: 100

split: 'train'

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}