defaults:
  - _self_
  - dataset: kinetics
  - feature_extractor: resnet2d1
  - model: vicregl
  # - experiments: "/home/sdastani/projects/rrg-ebrahimi/sdastani/SSL_video/experiments"

split: 'train'

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}