name: kinetics

NUM_CLASSES: 400
NUM_FRAMES: 8
SAMPLING_RATE: 32
TRAIN_JITTER_SCALES: [256, 320]
TRAIN_CROP_SIZE: 224
TEST_CROP_SIZE: 224
INPUT_CHANNEL_NUM: [3]
PATH_LABEL_SEPARATOR: " "

# Dataloader configs
NUM_WORKERS: 12
PIN_MEMORY: True